server:
  port: 8082

spring:
  application:
    name: doctor-service
  datasource:
    url: jdbc:mysql://localhost:3306/doctor_db
    username: root
    password: Mayank1999#
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka